### ISSUE TITLE
NEON Bug: not passing private static readonly string[] arrays properly...

### ISSUE THREAD

**Issue by mwherman2000** [neo-project/neo-compiler#106]
https://github.com/mwherman2000/examples-csharp/blob/master/SupportedStandards1/Contract1.cs#L18
is producing a different result compared to:
https://github.com/mwherman2000/examples-csharp/blob/master/SupportedStandards1/Contract1.cs#L19

The difference is one string array is declared 

`private static readonly string[] _supportedStandards1 = { "NEP-5", "NEP-1234" };`

and the other is declared on the stack...

`string[] _supportedStandards2 = { "NEP-5", "NEP-1234" };`

Here's an example....

![private-static-readonly-string-array-bug](https://user-images.githubusercontent.com/6101736/39382099-7b0ad6d8-4a32-11e8-9976-32ebe6124c5e.png)

**Comment by lightszero** [comment]
i think string[] is not a simple type.i will add a compiler error for that.
