### ISSUE TITLE
neon 2.3.0.0 fails to compile when using StorageMap in certain locations

### ISSUE THREAD

**Issue by birmas** [neo-project/neo-compiler#113]
The example provided below will fail to compile with the error `CONVERTTASK : Convert error : System.Exception: cannot convert addr in: System.Void TestCreateMapContract.Contract1::Main()`

If you uncomment either of the indicated lines, prior to the if statement, compiler will work properly. Compiler will also work properly when tmp is replaced with true in the if statement.

```using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;
 
namespace TestCreateMapContract
{
    public class Contract1 : SmartContract
    {
        public static void Main()
        {
            // uncomment the below line to make it compile ok
            //StorageMap mymap = Storage.CurrentContext.CreateMap("mapprefix");
            // or you could uncomment this line to make it compile ok
            //int x = 1;
            bool tmp = true;
            if (tmp)
            {
                return;
            }
 
            StorageMap testmap = Storage.CurrentContext.CreateMap("mapprefix");
        }
    }
}
```

**Comment by shargon** [comment]
Verified and strange behaviour

**Comment by birmas** [comment]
confirmed this is resolved with the commit from @lightszero - thanks for the fast fix!
