### ISSUE TITLE
NEP8 compiler changes break previously working projects

### ISSUE THREAD

**Issue by birmas** [neo-project/neo-compiler#116]
Recent changes to the compiler have left previously working contracts in a state of failure. The sample project consists of a C# contract with two simple CS files (see below)

When building with compiler 2.0.3.6 (commit: b18eb64540ece8e77c2d94d85ba5a273465f2d92) this contract will build and deploy successfully and can be invoked. Opcode for compiled project is: 
>52c56b6c766b00527ac46c766b51527ac46104617364666165080061616c756651c56b6c766b00527ac4616168164e656f2e53746f726167652e476574436f6e7465787407626c61686b65796c766b00c3615272680f4e656f2e53746f726167652e50757461616c7566

The fault was introduced in commit 0ebc569564e8b229719493c2e285a30ac16d8cfd and when building with compiler 2.3.0.x the contract will build and deploy successfully but cannot be invoked (invocation will result in an execution terminated in fault state message in neo-gui). Opcode for compiled project is:
>52c56b6c766b00527ac46c766b51527ac461046173646661e00001080061616c756651c56b6c766b00527ac4616168164e656f2e53746f726167652e476574436f6e7465787407626c61686b65796c766b00c3615272680f4e656f2e53746f726167652e50757461616c7566

I think being able to layout and access additional classes in your contract this way is a reasonable expectation and the compiler should continue to support this feature.

### Contract1.cs
```
namespace Neo.SmartContract
{
    public class Contract1 : Framework.SmartContract
    {
        public static void Main(string operation, params object[] args)
        {
            Contract2.WriteStorage("asdf");
        }
    }
}
```

### Contract2.cs
```
using Neo.SmartContract.Framework.Services.Neo;

namespace Neo.SmartContract
{
    public class Contract2 : Framework.SmartContract
    {
        public static void WriteStorage(string blah)
        {
            Storage.Put(Storage.CurrentContext, "blahkey", blah);
        }
    }
}
```
NB: although I have given an example of the classes split into separate files, the following code results in the exact same bytecode with compiler 2.3.0.0

### ContractSingleFile.cs
```
using Neo.SmartContract.Framework.Services.Neo;

namespace Neo.SmartContract
{
    public class Contract1 : Framework.SmartContract
    {
        public static void Main(string operation, params object[] args)
        {
            Contract2.WriteStorage("asdf");
        }
    }

    public class Contract2 : Framework.SmartContract
    {
        public static void WriteStorage(string blah)
        {
            Storage.Put(Storage.CurrentContext, "blahkey", blah);
        }
    }
}
```
>52c56b6c766b00527ac46c766b51527ac461046173646661e00001080061616c756651c56b6c766b00527ac4616168164e656f2e53746f726167652e476574436f6e7465787407626c61686b65796c766b00c3615272680f4e656f2e53746f726167652e50757461616c7566

**Comment by lllwvlvwlll** [comment]
@shargon @AshRolls

**Comment by birmas** [comment]
Additionally, I have tried updating my copy of neo-gui to use the latest neo-vm - this results in the evaluation stack no longer being exposed. Exposing ApplicationEngine.CurrentContext.EvaluationStack didn't work - I'm not sure what the plan is for updating neo-gui with the latest neo-vm.

**Comment by shargon** [comment]
We need to change the gui and cli for the last changes of NEP-8, this changes are included on https://github.com/neo-project/neo/pull/288
