### ISSUE TITLE
variables in contracts class causes exception

### ISSUE THREAD

**Issue by birmas** [neo-project/neo-compiler#119]
Consider the following examples:
```
using Neo.SmartContract.Framework.Services.Neo;

namespace Neo.SmartContract
{
    public class Contract1 : Framework.SmartContract
    {
        public static string TestString() => "asdf";
        public static void Main(string operation, params object[] args)
        {
            Contract2.TestString();
        }
    }

    public class Contract2 : Framework.SmartContract
    {
        public static void TestString()
        {
            Runtime.Notify("Contract1.TestString()", Contract1.TestString());
        }
    }
}
```

Upon invocation we receive the expected response:
>[SmartContract.Runtime.Notify][335933] [b422551bacf4dbd293721b760a45b49a8257e0c8] [tx 05536b8f1e90235494fa2502f7a3da4b704be4eef6743bcb6867be0eee3aeb5c] [b'Contract1.TestString()', b'asdf']

Using a slight variation where we use a variable instead of a method for `TestString`:
```
using Neo.SmartContract.Framework.Services.Neo;

namespace Neo.SmartContract
{
    public class Contract1 : Framework.SmartContract
    {
        public static string TestString = "asdf";
        public static void Main(string operation, params object[] args)
        {
            Contract2.TestString();
        }
    }

    public class Contract2 : Framework.SmartContract
    {
        public static void TestString()
        {
            Runtime.Notify("Contract1.TestString", Contract1.TestString);
        }
    }
}
```
Results in a faulted execution state. I have tested this with other variable types with the same results. Integers appears to work but most other variables will fail (sometimes silently after invocation). I believe expected behaviour should be for variables, regardless of type, to be available to other classes within the contract unless they are set as private.

**Comment by lightszero** [comment]
I missed this,because neovm is methodbase, you can't fix a static variable.
so we need to use variable like this:

public static readonly string TestString = "asdf";

or

const string  TestString = "asdf";

**Comment by lightszero** [comment]
I will throw some Error when user defined a  static variable without  readonly or  const.
