### ISSUE TITLE
Install Instructions?

### ISSUE THREAD

**Issue by aaroncatalano** [neo-project/neo-compiler#123]
how exactly do you install this solution in VS Studio 2015 on Windows? When I click both Neon and Neo-Compiler in the downloaded folders that I have unzipped it throws errors in VS Studio. Please provide install instructions.

**Comment by aaroncatalano** [comment]
I have already install the Neo plugin for Visual Studio 2015 successfully.

**Comment by birmas** [comment]
Please provide details of the errors.

I've no trouble setting this up in vs community 2017 by following the docs on neo.org

**Comment by birmas** [comment]
@aaroncatalano  What does that have to do with neo-compiler? The CoZ privatenet docker has absolutely nothing to do with compiling neo-compiler in VS.. 😕

**Comment by aaroncatalano** [comment]
I will close the issue.  I see the compiler is supported by VS 2017 and not
2015.

**Comment by aaroncatalano** [comment]
The NEO-Compiler is supported by VS 2017, not VS 2015. Thank you for the feedback
