### ISSUE TITLE
Wrong compilation for != strings

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-compiler#132]
We found a issue with `string` comparisons, the equal works, but the distinct don't

If you see this sample, and send a parameter `text="hello";`

```csharp
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;

namespace Red4Sec
{
    public class Sample : SmartContract
    {
        public static bool Main(string text)
        {
            if (text == "hello") Runtime.Log("Is hello");
            if (text != "bye") Runtime.Log("Is not bye");
            return true;
        }
    }
}
```
The expected result is:
```
Is hello
Is not bye
```

The first condition is good

![image](https://user-images.githubusercontent.com/3167973/46127610-7e1fcf00-c231-11e8-8400-82fd0a61cf7e.png)

With the equal, all works

![image](https://user-images.githubusercontent.com/3167973/46127696-bb845c80-c231-11e8-9b07-20f4757ae781.png)

But the second one, with `!=` , is wrong translated

![image](https://user-images.githubusercontent.com/3167973/46127932-639a2580-c232-11e8-93f0-4b28ef98c838.png)

At this moment, the stack is good, but this `INVERT` produce undesired results, and the result is wrong

![image](https://user-images.githubusercontent.com/3167973/46128024-a825c100-c232-11e8-8cae-9aa5852b3da7.png)

So the result is this:

```
Is hello
```

**Comment by lightszero** [comment]
very helpful,that will be fixed soon with your help.

**Comment by lightszero** [comment]
but this bug had be fixed in #126 ,maybe you test with an old version?

**Comment by shargon** [comment]
I will check it! maybe is my fault and was tested with old version!

**Comment by shargon** [comment]
Yes, is my fault! thanks for the support @lightszero !
