### ISSUE TITLE
Byte initialization made as BigInteger

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo-compiler#134]
In a discussion at neo-vm https://github.com/neo-project/neo-vm/pull/60, I noticed that byte initializations are being performed as BigInteger.
Example:
```cs
        public static int Main() {
            return 255;
        }
```
Issues: `02 PUSHBYTES2 ff00` (ok, because 255 is interpreted as BigInteger)

However, explicit byte should be treated as real byte. Example, `0xff` should issue PUSH `ff` not `ff00`
```cs
        public static byte Main() {
            return 0xff;
        }
```
But it issues: `02 PUSHBYTES2 ff00` (because 255 is interpreted as BigInteger)

I'm not sure if these are the correct lines:
https://github.com/neo-project/neo-compiler/blob/master/neon/MSIL/Converter.cs#L892-L907

Do you think it's possible to insert a `else if (_src is byte)`?

**Comment by igormcoelho** [comment]
It's interesting that, when issuing a byte[] directly, it uses the byte conversion correctly:
```cs
            byte[] unique = {255};
            barray[2] = unique[0];
```
An instruction `01 PUSHBYTES1 ff` is created. Is that related to `getNumber(...)` method?

**Comment by erikzhang** [comment]
A `byte` is unsigned and a `BigInteger` is signed. But in NeoVM, there are only `BigInteger` and `byte[]`, not `byte`.

So we have to use `BigInteger` instead of `byte`. `ff == -1`, `ff00 == 255`, `-1 != 255`. So `ff != ff00`.

**Comment by igormcoelho** [comment]
I agree that there's no byte on neovm, but we can push a ByteArray with a single element... that works better than BigInteger when we want an explicit byte.

**Comment by igormcoelho** [comment]
Problem is deeper than I thought... it seems C# MSIL is automatically converting bytes to int32.
```cs
        public static bool Main()
        {
            byte[] b = {0x01, 0x02};
            return b[0]==0xff;
        }
```
```
CODE:
  Ldc_I4_2
  CODE:
  Newarr
  CODE:
  Ldc_I4_0
  CODE:
  Ldelem_U1
  CODE:
  Ldc_I4
  CALLING _ConvertPushI4WithConv
  255
  CODE:
  Ceq
  NUMEQUAL .Ceq
  CODE:
  Ret
```
```
00 PUSH0  #An empty array of bytes is pushed onto the stack
c5 NEWARRAY  #
6b TOALTSTACK  # Puts the input onto the top of the alt stack. Removes it from the main stack.
02 PUSHBYTES2 0102 # 
00 PUSH0  #An empty array of bytes is pushed onto the stack
51 PUSH1  # The number 1 is pushed onto the stack.
7f SUBSTR  # Returns a section of a string.
02 PUSHBYTES2 ff00 # 
9c NUMEQUAL  # Returns 1 if the numbers are equal, 0 otherwise.
61 NOP  # Does nothing.
6c FROMALTSTACK  # Puts the input onto the top of the main stack. Removes it from the alt stack.
75 DROP  # Removes the top stack item.
66 RET  #
```

So, perhaps a better approach is to convert BigInteger to bytearray on high level, to get the last byte and perform the assignment.

**Comment by igormcoelho** [comment]
It looks like CIL (or MSIL) only push int32 to stack, not int8: https://en.wikipedia.org/wiki/List_of_CIL_instructions
Strangely enough, this scenario returns false instead of true:
```cs
        public static bool Main( ) {
            byte[] b = {0xff, 0xfe};
            return b[0] == 0xff; // returns false
        }
```
Because the last 0xff is pushed as 255, which is 0xff00 (different from 0xff). It looks like all numbers are automatically converted to 'int' on C#, so we need an explicit conversion to byte.
```cs
            byte[] b = {0xff, 0x01};
            BigInteger bi = 0xff;
            return (b[0] == bi.AsByte()) && (b[1]==0x01.AsByte()); // returns true
```

**Comment by igormcoelho** [comment]
@erikzhang I will close this issue because it seems impossible to detect a byte, because CIL (or MSIL) will convert it automatically to int32. So, I will propose something else on higher level, to do byte[] operations safely.
