### ISSUE TITLE
Neon 2.3.0.9 generating invalid AVM

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-compiler#137]
Hello,
I used neon to compile my project, and the resulting AVM seems to be invalid. 
I decompiled it with neo-debugger and neo eco lab and both complain about two invalid opcodes in my AVM: `0x70` and `0xe0`.
Here is the link to my avm: 
https://www.dropbox.com/s/5or94l0yqqru445/SimpliPay.avm?dl=0

I don't discard the problem being in my code, but since neon compiled it, I believe that we may have a problem in the compiler (it should have throw error instead of compiling?).

**Comment by erikzhang** [comment]
`E0` is `CALL_I`:

https://github.com/neo-project/neo-vm/blob/248d77fc1962eaf7ff653bc0063f97b12804b153/src/neo-vm/OpCode.cs#L449

**Comment by lock9** [comment]
Hello,
Yes, I found that out later. The problem does not occurr with nep-8 disabled, but since there is no opcode with this value, maybe there is some kind of overflow happening.
I changed my code and it stabilized again, but I'm not sure if the opcodes gerenerated are correct. It might have generated wrong, but existing, opcodes. 
If I manage to isolate the problem I'll post again here.

**Comment by igormcoelho** [comment]
Grande Ricardo!!
Please run using --compatible mode... unless you really want nep8 now.

**Comment by igormcoelho** [comment]
In fact, I didn't follow this nep-8 story too much, and don't know these opcodes very well.. but I assume the compiler is right, perhaps our privatenets are not handling these opcodes correctly (at least this may be the case for neocompiler.io). 
Where did you put these empty brackets man? hahahaha inside a function? to reduce the scope of some variables? I'm not expert in C# either xD

**Comment by lock9** [comment]
Regarding the new error, this is my method. You will find the brackets near the end of it:

```C#
public static bool RegisterRegularAccount(object[] args)
        {
            if (args.Length != 3)
            {
                Runtime.Log("Invalid parameters for RegisterRegularAccount");
                return false;
            }

            byte[] newAccount = (byte[])args[0];

            if (newAccount.Length != 20)
            {
                Runtime.Log("Invalid parameters for ApproveRegularAccount");
                return false;
            }

            if (!Runtime.CheckWitness(newAccount))
            {
                Runtime.Log("Invalid signature for account " + newAccount);
                return false;
            }


            byte[] currentAccount = BankDao.GetRegularAccount(newAccount);
            if (currentAccount.Length != 0)
            {
                Runtime.Log("Account already exists " + newAccount);
                return false;
            }

            byte[] publicKey = (byte[])args[1];
            byte[] signature = (byte[])args[2];

            if (publicKey.Length == 0)
            {
                Runtime.Log("Invalid public key");
                return false;
            }


            if (signature.Length == 0)
            {
                Runtime.Log("Invalid Signature");
                return false;
            }
            // In the compiler or .net kit
            {

            }

            Map<string, object> accountMap = new Map<string, object>();
            accountMap["publicKey"] = publicKey;
            accountMap["signature"] = signature;

            BankDao.PersistRegularAccount(newAccount, accountMap.Serialize());
            Runtime.Log("New account registration");

            return true;
        }  ```

If I remove those open / close brackets, I have the error:
EXEC : Convert error : System.Exception: cannot convert addr in: System.Boolean SimpliPay.BankProcess::RegisterRegularAccount(System.Object[])
1>
1>     at Neo.Compiler.MSIL.ModuleConverter.ConvertAddrInMethod(NeoMethod to) in C:\Workspace\neo-debugger-tools\NEO-Compiler\MSIL\Converter.cs:line 427
1>     at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to) in C:\Workspace\neo-debugger-tools\NEO-Compiler\MSIL\Converter.cs:line 354
1>     at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in, ConvOption option) in C:\Workspace\neo-debugger-tools\NEO-Compiler\MSIL\Converter.cs:line 187
1>     at Neo.Compiler.AVM.AVMCompiler.Execute(String filename, String filepdb, ILogger log) in C:\Workspace\neo-debugger-tools\NEO-Compiler\AVM\AVMCompiler.cs:line 68

**Comment by igormcoelho** [comment]
Strange, looks like it's failing here @lock9 :+1: 
https://github.com/neo-project/neo-compiler/blob/d6e18710a43b1fbd83452f6a3e3f8e8bb5b7fa98/neon/MSIL/Converter.cs#L424
At ConvertAddrIn method. I don't know what it does...

At neocompiler.io we are using 21 november version (commit 51ea9c70ddb9c3fbd6ea71b3195685fb659ea0c8),  and it fails like this. Does it compile in any version?

**Comment by vncoelho** [comment]
In neocompiler we also have support to multiple version, take a try with other version, @lock9 
You can pick from the selection box

![image](https://user-images.githubusercontent.com/17395762/49483432-4711ff00-f81a-11e8-90f5-b2b5e301fa39.png)

I am trying to printscreen but I can't.
![image](https://user-images.githubusercontent.com/17395762/49483388-18942400-f81a-11e8-9358-794d72824ba3.png)

**Comment by igormcoelho** [comment]
Rick my friend, this doesn't look like any recent problem... this simple code is also breaking with same error:
```cs
using Neo.SmartContract.Framework.Services.Neo;
using Neo.SmartContract.Framework;
namespace RickSpace
{
	class RickDapp : SmartContract
	{
        public static bool Main(object[] args)
        {
            byte[] test = (byte[])args[0];
            
            if (test.Length == 0)
                return false;
            
            Map<string, object> m = new Map<string, object>();
            return true;
        }
    }
}
```

**Comment by igormcoelho** [comment]
These are the MSIL instructions:
```
   IL_0000: ldc.i4.s 10
  10
  
  IL_0002: brtrue.s IL_0006
  IL_0006: newobj System.Void Neo.SmartContract.Framework.Map`2<System.String,System.Int32>::.ctor()
  
  IL_0004: ldc.i4.0
  
  IL_0005: ret
  
  IL_0006: newobj System.Void Neo.SmartContract.Framework.Map`2<System.String,System.Int32>::.ctor()
  System.Void Neo.SmartContract.Framework.Map`2<System.String,System.Int32>::.ctor()
  
  IL_000b: pop
  
  IL_000c: ldc.i4.1
  
  IL_000d: ret
EXEC : Convert error : System.Exception: cannot convert addr in: System.Boolean RickSpace.RickDapp::Main() [/tmp/NeoContract1/NeoContract1.csproj]
```

**Comment by igormcoelho** [comment]
@lightszero I think I know the cause:

```cs
using Neo.SmartContract.Framework.Services.Neo;
using Neo.SmartContract.Framework;
using Neo.VM;
using System.Numerics;
namespace RickSpace
{
	class RickDapp : SmartContract
	{
	    public class Y
	    {
	        [OpCode(OpCode.NOP)]   // <--------- REMOVE THIS AND IT WORKS!
	        public extern Y();
	    }
	    
        public static bool Main()
        {
            int x = 3;
            if (x == 0)
                return false;
            Y y = new Y();
            return true;
        }
    }
}
```

**Comment by lightszero** [comment]
a minimal smartcontract code with bug is very useful for find bug.

using Neo.SmartContract.Framework.Services.Neo;
using Neo.SmartContract.Framework;
namespace RickSpace
{
	class RickDapp : SmartContract
	{
        public static bool Main()
        {
            int x = 10;
            if (x == 0)
                return false;
            // < ----------- put anything here and it will work!   It can be a random initialization, function call... anything.
            Map<string, int> m = new Map<string, int>();
            return true;
        }
    }
}

i will start from here.
