### ISSUE TITLE
OpCode.CAT 的问题

### ISSUE THREAD

**Issue by ttblack** [neo-project/neo-compiler#145]
我更新了最新的合约编译器neo_compiler后，下面的合约会编译出错 。
byte[] a1 = new byte[] { 1, 2, 3 };

byte[] a2 = new byte[] { 4, 5, 6 };

byte[] a3 = a1.Concat(a2);

出错信息为：
:IL_0104 Call System.Byte[] Neo.SmartContract.Framework.Helper::Concat(System.Byte[],System.Byte[]) ---> System.InvalidCastException: Unable to cast object of type 'System.Byte' to type 'Mono.Cecil.CustomAttributeArgument[]

出错的地方在Conv_Multi.cs 中的315行.
   if (attr.AttributeType.Name == "OpCodeAttribute")
                {
                    var type = attr.ConstructorArguments[0].Type;
                    Mono.Cecil.CustomAttributeArgument[] val = (Mono.Cecil.CustomAttributeArgument[])attr.ConstructorArguments[0].Value;

原因像是会把attr.ConstructorArguments[0].Value 不能转换成 Mono.Cecil.CustomAttributeArgument[]

**Comment by igormcoelho** [comment]
We need to approve the pending PR on devpack and compiler, to launch a new version @lightszero.

**Comment by lightszero** [comment]
他说你应该是 只更新了编译器，没有更新 devpack @ttblack
