### ISSUE TITLE
create branch master 2.x

### ISSUE THREAD

**Issue by lightszero** [neo-project/neo-compiler#155]
NeoVM 3.x and 2.x is very different for now.

create branch master-2.x for compiler2

use branch master for compiler3.

but neovm3 had not be published on nuget,compiler3 can not build directly.

**Comment by shargon** [comment]
Is not created yet?

**Comment by vncoelho** [comment]
Agree, lights.

There is already a branch https://github.com/neo-project/neo-compiler/tree/master-2.x

Maybe it need to be restarted.

**Comment by lightszero** [comment]
I created that 1 mintue ago.

**Comment by lightszero** [comment]
can we use master for compiler 3
master-2.x for compiler 2
agree?

**Comment by lightszero** [comment]
we still have other problem.

neovm 3 not on nuget for now.

compiler3 need neovm3

**Comment by shargon** [comment]
You can use this https://github.com/neo-project/neo/blob/master/neo/neo.csproj#L31

**Comment by lightszero** [comment]
> You can use this https://github.com/neo-project/neo/blob/master/neo/neo.csproj#L31

yes,thank you.I missed that.

but still neovm 3 use the same package name with neo2.

so people will confuse in future.
neovm3 and neovm2 is not different version.
they are not different lib.

**Comment by lightszero** [comment]
neo3'lib had be publish on MyGet-neo, my fault.

for package name problem ,add another issue

https://github.com/neo-project/neo/issues/756

**Comment by vncoelho** [comment]
Why the master 2.x is 15 commits ahead, @lightszero?

Maybe it can be forked again.
