### ISSUE TITLE
(neoj) Integer.valueOf

### ISSUE THREAD

**Issue by wy** [neo-project/neo-compiler#16]
The method call for Integer.valueOf(int i) has error compilations and is not supported.

For Kotlin, when you define Int i = 3, it compiles to Java bytecode as Integer i = Integer.valueOf(int i).

You can get around this by using BigInteger however Int should be supported in neoj.

Thanks
Wing

**Comment by lightszero** [comment]
i can not repetition it，show more code maybe help？
use IDEA

**Comment by lightszero** [comment]
fixed
