### ISSUE TITLE
Kotlin Is nullable check

### ISSUE THREAD

**Issue by wy** [neo-project/neo-compiler#17]
Kotlin tries to solve a big issue with Java development which is the unexpected Null Pointer Exception.

In order to do this, it tries to enforce all the way through the chain that Objects (everything is an object even primitives) that they cannot be null.

It has a special method that it calls **kotlin.jvm.internal.Intrinsics::checkExpressionValueIsNotNull**. This should be supported by neoj.

**Comment by lightszero** [comment]
fix it
