### ISSUE TITLE
Runtime in Java Framework not yet there

### ISSUE THREAD

**Issue by wy** [neo-project/neo-compiler#18]
Java framework and neoj compiler needs to support the Runtime methods:

Runtime.Log
Runtime.CheckWitness
Runtime.Notify
Runtime.Trigger

As well as TriggerType.Verification.

This will allow the csharp examples to be ported to Java (and Kotlin)

**Comment by erikzhang** [comment]
I will do it next week.

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-devpack-java
