### ISSUE TITLE
Unsupported instruction lookupswitch

### ISSUE THREAD

**Issue by notatestuser** [neo-project/neo-compiler#24]
Used extensively in kotlin as its `when` expression is important

JVM bytecode:
<img width="318" alt="screen shot 2017-09-16 at 14 06 16" src="https://user-images.githubusercontent.com/1255926/30509657-ac707988-9a7b-11e7-8ccc-8630d65acc6d.png">

Compiler output:
<img width="584" alt="screen shot 2017-09-16 at 14 12 51" src="https://user-images.githubusercontent.com/1255926/30509691-3407ab3c-9a7c-11e7-99cc-5a38b5576eab.png">

I guess that it could just handled as a chain of `if`/`if else`/`else`

@wy, not sure if you've seen this in kotlin too?

**Comment by wy** [comment]
Yes. For now you can replace with more verbose if statements but ideally
should be supported

**Comment by notatestuser** [comment]
Another unhandled one that seems more essential: `ACONST_NULL`

Appears when you have a `null` in your code

**Comment by lightszero** [comment]
Could you show some kotlin code here?

**Comment by notatestuser** [comment]
Sure @lightszero 

`LOOKUPSWITCH`:
```kt
when (op) {
   "A" -> return A()
   else -> return B()
}
```

`ACONST_NULL`:
```kt
return null
```

**Comment by lightszero** [comment]
has fixed
