### ISSUE TITLE
More missing things for kotlin

### ISSUE THREAD

**Issue by notatestuser** [neo-project/neo-compiler#27]
* `Convert Error:System.Exception: new not supported type.kotlin.TypeCastException`
   Happens when passing a non-nullable type to a class method:
  ```kt
  method(args[0] as Long)
  ```

* `Convert Error:System.Exception: unsupported instruction __getfield`
    ```kt
    class Contract : SmartContract() {
       private val FEE = BigInteger.valueOf(1)
       // … later …
       fun method() {
          FEE.multiply(factor)
     ```
* `Convert Error:System.Exception: unknown call:java.lang.Long::longValue`
   (important, required to use BigInteger.valueOf() with a nullable long)
   ```kt
   class Contract : SmartContract() {
      fun Main(vararg args: Object) : Object? {
         method(args[0] as Long?)
         return false
      }
      fun method(factor: Long?) {
         private val FEE = BigInteger.valueOf(1)
         val fee = FEE.multiply(BigInteger.valueOf(factor ?: 1))  // <- happens here
         // ...
   ```

**Comment by lightszero** [comment]
1 has fixed
2 we cant use memberfield
3 working on it.

**Comment by notatestuser** [comment]
What can we use instead of memberfield?
