### ISSUE TITLE
unknown call:System.Boolean Neo.SmartContract.Framework.SmartContract::VerifySignature ...

### ISSUE THREAD

**Issue by notatestuser** [neo-project/neo-compiler#28]
What happened to `VerifySignature`?

Neo.Compiler.MSIL console app v2.0.3.0
Convert Error:System.Exception: unknown call:System.Boolean Neo.SmartContract.Framework.SmartContract::VerifySignature(System.Byte[],System.Byte[])

Happens when a contract is compiled to target netstandard1.6

**Comment by notatestuser** [comment]
@lightszero any thoughts?

**Comment by lightszero** [comment]
maybe you need this.
https://github.com/neo-project/neo-devpack-dotnet

**Comment by notatestuser** [comment]
I think this was because I was using netstandard1.6. It is OK in NET 4.0
