### ISSUE TITLE
Problem to compile project with neoj

### ISSUE THREAD

**Issue by elvega** [neo-project/neo-compiler#55]
Hi,

I have a problem to compile neoj, I write the next command in cmd windows:

neoj.exe HelloWorldSmartContrat

and the exception shown is:
C:\Users\0014372\eclipse-workspace\HelloWorldSmartContracts\src>neoj.exe HelloWo
rld.class
Neo.Compiler.JVM console app v2.0.3.0
Convert Error:System.TypeInitializationException: The type initializer for 'Syst
em.Diagnostics.ProcessManager' threw an exception. ---> System.BadImageFormatExc
eption: An attempt was made to load a program with an incorrect format. (Exception
 from HRESULT: 0x8007000B)
   at Interop.mincore.LookupPrivilegeValue(String lpSystemName, String lpName, L
UID& lpLuid)
   at System.Diagnostics.ProcessManager..cctor()
   --- End of inner exception stack trace ---
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 acces
s, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolea
n firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Neo.Compiler.Program.Main(String[] args)

What is the problem?

Thanks

**Comment by lightszero** [comment]
could you give me the .class file?

**Comment by elvega** [comment]
[HelloWorld.zip](https://github.com/neo-project/neo-compiler/files/1415120/HelloWorld.zip)

**Comment by lightszero** [comment]
and this is the test
```
dotnet neoj.dll d:\HelloWorld.class
Neo.Compiler.JVM console app v2.0.3.0
Convert Error:System.Exception: 找不到入口函数，请检查
   at Neo.Compiler.JVM.ModuleConverter.Convert(JavaModule _in) in D:\git\neo\neo-compiler\neoj\JVM\Converter.cs:line 117
   at Neo.Compiler.Program.Main(String[] args) in D:\git\neo\neo-compiler\neoj\Program.cs:line 45

```

you can try to copy this file to another place first.

**Comment by elvega** [comment]
what file? HelloWorld.class or neoj.dll?? and in the what directory?

**Comment by fabwa** [comment]
I get `Convert Error:System.Exception: 找不到入口函数，请检查`. Which is another issue (chances are your Main function has no capital 'M'. Your issues seems to be related to the compiler itself. How did you compile it?

**Comment by elvega** [comment]
I have compiled with the IDE  eclipse with the next steps:
Project-> Build All
execute cmd in windows and execute neoj.exe HelloWorld.class 
the next error is showed:
![captura](https://user-images.githubusercontent.com/32299730/32091315-e47f7354-baf3-11e7-97a0-66932a8b27a8.PNG)

**Comment by lightszero** [comment]
do you copy neoj.exe to here?it need many other files too.

**Comment by elvega** [comment]
neoj.exe isn't in this directory, neoj.exe is defined as an enviroment variable and is in a different directory of HelloWorld.class

**Comment by lightszero** [comment]
now we got it. we publish a win10-w64 exe.
you can publish a win7-x86 if you use a windows 7.
you can use this bat file

https://github.com/neo-project/neo-compiler/blob/for_x86_build/publish_x86.bat
