### ISSUE TITLE
JVM method overloading

### ISSUE THREAD

**Issue by notatestuser** [neo-project/neo-compiler#60]
Multiple methods should be able to share the same name, see below:
```kt
private fun log_info(msg: String) {
   if (LOG_LEVEL > 1) Runtime.notify(msg)
}
private fun log_info(msg: String, arg: Any) {
   if (LOG_LEVEL > 1) Runtime.notify(msg, arg)
}
```
OR throw a compiler error. Now this code compiles but only one of the methods is ever executed, putting the VM in a bad state.

**Comment by lightszero** [comment]
en,throw a error is simple.maybe neon has this issue too.i will do that.

**Comment by lightszero** [comment]
fixed
https://github.com/neo-project/neo-compiler/pull/64
