### ISSUE TITLE
Can't find neon.dll for win10-x64 - generate compiler seems to be impossible

### ISSUE THREAD

**Issue by kuzdu** [neo-project/neo-compiler#63]
I try to run neon compiler and do this tutorial here: http://docs.neo.org/en-us/sc/getting-started-csharp.html

I downloaded the project an try to publish like this: 
![publish_neo_compiler_msil_project](https://user-images.githubusercontent.com/7271766/32677759-f7c63a70-c65f-11e7-9130-14db2073640a.png)

But I always get the error: `File"obj\Release\netcoreapp1.0\win10-x64\neon.dll" can't copy because file not found`

And it's true. The file isn't in the path. 

![noneodll 2](https://user-images.githubusercontent.com/7271766/32678029-013cf002-c661-11e7-8c2a-6d4bd998a0de.png)

Where do I get the right `neon.dll` that I can start?

**Comment by lightszero** [comment]
now vs2017 has issue to publish net core project.
you can use cli code to do that.
d:\xxx\xx\neon\>dotnet publish -r win10-x64 -c release
or write a bat file to do that.

https://github.com/neo-project/neo-compiler/blob/for_x86_build/publish_x86.bat

**Comment by jesmith0** [comment]
I had the same issue as kuzdu and this resolved it for me. Thanks!
