### ISSUE TITLE
Not able to publish the neoj compiler

### ISSUE THREAD

**Issue by kiranjadhav1000** [neo-project/neo-compiler#66]
Hi,
I m a java developer. no idea abt .net.
When i was trying to publish neoj compiler i m getting popup saying 'Publish failed'.
Specific Error: "Could not copy the file "obj\Release\netcoreapp1.1\win10-x64\neoj.dll" because it was not found."

PFA: Error log and error screenshot of Visual studio.

Note : I m using windows 10 32 bit os.

Let me know if u need more info.
![error_screenshot](https://user-images.githubusercontent.com/32902961/33055231-4cc51658-cea4-11e7-9dcd-7d68b4c900dd.PNG)

[ErrorLog_VisualStudio.txt](https://github.com/neo-project/neo-compiler/files/1490040/ErrorLog_VisualStudio.txt)

**Comment by jdaless** [comment]
I am having the same issue with the neon compiler. I am on win10 64 bit though. 

1>------ Publish started: Project: neon, Configuration: Release Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\csc.exe 
1>Could not copy the file "obj\Release\netcoreapp1.0\win10-x64\neon.dll" because it was not found.
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by chrisparkerrr** [comment]
@kiranjadhav1000 , I had the same issue here and the workaround was to use dotnet CLI for publishing.
Try:
`dotnet publish neoj.csproj -c Release -f netcoreapp1.1 -r win10-x64`
or in @jdaless case
`dotnet publish neon.csproj -c Release -f netcoreapp1.0 -r win10-x64`

Another workaround is by saving (creating) a publish profile before publishing.
Just click publish in the context menu of your project and follow the steps below:

![publish workaround](https://user-images.githubusercontent.com/10300609/33359536-6b28958a-d4b6-11e7-85e4-bbe6d4a99f85.png)

After doing this, just try publishing it normally.

PS: Interesting enough, this is only hapenning with neon and neoj projects, neoa is fine.

**Comment by kiranjadhav1000** [comment]
@chrisparkerrr Thanks for your help, my issue solved after using below command suggested by you.
dotnet publish neoj.csproj -c Release -f netcoreapp1.1 -r win10-x64

**Comment by giulopresti** [comment]
I'm having a differend error
_17/12/2017 22:17:30
System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.Model.DefaultPublishSteps.<>c__DisplayClass22_0.<IsBuildCompletedSuccessfully>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__108.MoveNext()
---> (Inner Exception #0) System.Exception: Publishing failed.<---_

do you have any idea how to solve it?

**Comment by supun-perera** [comment]
dotnet publish neon.csproj -c Release -f netcoreapp1.1 -r win10-x64
dotnet publish neoj.csproj -c Release -f netcoreapp1.1 -r win10-x64
dotnet publish neoa.csproj -c Release -f netcoreapp1.1 -r win10-x64

Worked for me.  thx @chrisparkerrr

**Comment by plash29** [comment]
@lightszero  I have same issue. I am using Windows 7 64-bit

**Comment by cobysolutions** [comment]
In the Profile Settings screen change your Target Location path to the project file neon.csproj location. Click save and then Publish. The path is most likely location moste likely will be C:\Users\...\Source\Repos\neo-compiler\neon
