### ISSUE TITLE
Add a compiler feature to support invoke another contract by dynamic contract address

### ISSUE THREAD

**Issue by luodanwg** [neo-project/neo-compiler#70]
### Abstract

Add a compiler feature to support invoke another contract by contract address.

### Motivation

If we want to invoke another contract at present, we must declare the address of contract by hard code, like this:

    using Neo.SmartContract.Framework;
    using Neo.SmartContract.Framework.Services.Neo;

    public class Lock : SmartContract
    {
        [Appcall("XXXXXXXXXX")]
        public static extern int AnotherContract(string arg);
        public static bool Main()
        {
            AnotherContract("Hello");
        }
    }

In some circumstances, we need to invoke another contract by contract address at runtime.

### Specification

The method we want compiler to support like this:

`object InvokeContract(byte[] contractAddress, object[] params)`

contractAddress is the contract address we want to invoke.
params are the parameters to invoke contract.
And the return type is object.

**Comment by erikzhang** [comment]
NEP-4 is being implemented: https://github.com/neo-project/proposals/pull/19
