### ISSUE TITLE
Add the support of define the variable with string.

### ISSUE THREAD

**Issue by luodanwg** [neo-project/neo-compiler#72]
### Abstract

Add the support of  define the variable with string.

### Motivation
if we want to define a address ,we now can only code by byte like below, which is very hard to read.
``` c#
public static readonly byte[] admin = { 146, 200, 116, 173, 138, 132, 16, 251, 229, 247, 170, 139, 222, 197, 89, 178, 83, 47, 112, 225 };
```
so can we define the variable like this 
[HexStringToByteArray("aabb1122")]
static byte[] message;
[AddressToScriptHash("ASwydXj735ASTwRjPdXppJqtvVUPzzeofB")]
static byte[] admin;

**Comment by lightszero** [comment]
I got a better way
https://github.com/neo-project/neo-compiler/pull/73
