### ISSUE TITLE
(neoj) Problem when calling multi-argument methods from Java

### ISSUE THREAD

**Issue by jeisses** [neo-project/neo-compiler#79]
Hi all,

I'm having a problem when running smart contracts that call a multi-argument method from Java. The Neo VM faults when executing the call, it happens for any method that accepts more than 1 argument.

Minimal example:

```java
import org.neo.smartcontract.framework.SmartContract;

public class Calc extends SmartContract
{
    public static int Main() {
	return Add(7, 7);
    }

    public static int Add(int a, int b) {
	return a + b;
    }
}
```
Compiled using neoj:

```
51c56b575761617c6507006c75666151c56b6a00527ac46a51527ac46a00c36a51c3936c756661
```

This code results in a FAULT when run

When debugging the bytecode I notice that it creates an array of size 1 for the arguments (after the CALL), and it faults when trying to store (SETITEM) the second argument.

Is this a problem in the compiler, or do I suffer from a version mismatch or something similar?

**Comment by lightszero** [comment]
I had tested with eclipse and the newest neoj and it 's fine.
and this avm igot:
51c56b575761617c6507006c756661 53 c56b6a00527ac46a51527ac46a00c36a51c3936c756661
this is your avm.
51c56b575761617c6507006c756661 51 c56b6a00527ac46a51527ac46a00c36a51c3936c756661
![tim 20171223070400](https://user-images.githubusercontent.com/2275164/34314540-7c7b75c6-e7af-11e7-9159-6e0f4b2ac780.png)

**Comment by jeisses** [comment]
Thanks a lot for checking.

I found that the compilation of the java code is the problem. If I enable debugging information during compilation of the `.class` using the `-g` flag:

```
javac -cp ./org.neo.smartcontract.framework.jar -g Calc.java
```

I get the correct avm bytecode. Compiling in Eclipse also works.

I guess the debugging info is needed by noej. Shall I add this to the docs somewhere?

**Comment by lightszero** [comment]
very helpful.
