### ISSUE TITLE
ABI extension proposal

### ISSUE THREAD

**Issue by luodanwg** [neo-project/neo-compiler#93]
Does the ABI can provide a mark, which can identifies the function whether perform onchain or offchain.

So the dapp developer needn't to care about the the smart contract detail or use which protocal to interact with the blockchain. SDK will use ABI to  decided whether query on the node or make a transaction on the blockchain.

**Comment by erikzhang** [comment]
Does this change NEP-3? If so, can you port it to https://github.com/neo-project/proposals?

**Comment by luodanwg** [comment]
thanks , I have prot it to https://github.com/neo-project/proposals/issues/28
